/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisPage: typeof import('./src/components/AnalysisPage.vue')['default']
    ClipboardContentPage: typeof import('./src/components/ClipboardContentPage.vue')['default']
    ClipboardPage: typeof import('./src/components/ClipboardPage.vue')['default']
    DarkModeToggle: typeof import('./src/components/DarkModeToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Header.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MinecraftMotdPage: typeof import('./src/components/MinecraftMotdPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SensitivePage: typeof import('./src/components/SensitivePage.vue')['default']
  }
}
